### ISSUE TITLE
Windows line endings prevent running npm start on mac/linux

### ISSUE THREAD

**Issue by wiseolddj** [jsreport/jsreport-studio-dev#2]
`env: node\r: No such file or directory`

#! in the .bin scripts prevent mac/linux from running the scripts when following https://jsreport.net/learn/custom-recipe instructions.

**Comment by pofider** [comment]
This was already fixed https://github.com/jsreport/jsreport-studio-dev/releases/tag/1.0.2

However the update was not propagated to [jsreport-extension-starter-kit](https://github.com/jsreport/jsreport-extension-starter-kit)

I've fixed it now - https://github.com/jsreport/jsreport-extension-starter-kit/commit/54a5af9e261243ff8dead9cb9e3caf0f02da9aff
Please do pull and try again

**Comment by pofider** [comment]
Please let me know if it did help, I would close this afterwards.

**Comment by wiseolddj** [comment]
This is now working. Thanks.
